name: CI

on:
  push:
    branches: [main, develop]
    paths-ignore:
      - '**/*.md'
      - '**/*.sh'
      - '**/*.yaml'
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main, develop]
    paths-ignore:
      - '**/*.md'
      - '**/*.sh'
      - '**/*.yaml'

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
    steps:
      # actions/checkout@v6
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 0
      # actions/setup-java@v5
      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Gradle
        # gradle/actions/setup-gradle@v6
        uses: gradle/actions/setup-gradle@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e
        with:
          cache-provider: basic
      - name: Test and assemble
        run: ./gradlew test assemble
